# Generated by Django 4.2.3 on 2023-08-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('expiry', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('strike', models.CharField(max_length=50)),
                ('lotsize', models.CharField(max_length=50)),
                ('instrumenttype', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('exch_seg', models.CharField(max_length=20)),
                ('tick_size', models.CharField(max_length=20)),
            ],
        ),
    ]
