name: Docker CI/CD
on:
  push:
    branches:
      - main
jobs:
  build-test-deploy:
    runs-on: runner1
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with: 
          context: .
          push: true
          tags: uvaiskh/alogoapp:${{ github.sha }}

      - name: Deploy to EC2 Instance
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop algoapp || true
            docker rm algoapp || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/algoapp:{{ github.sha }}
            docker run -d --name algoapp -p 80:80 ${{ secrets.DOCKER_USERNAME }}/algoapp:{{ github.sha }}
            
        
